### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by solipsis**
Python 3 support for keepkey library. Credit to @romanz

### CODE REVIEW

**Comment by ngmiller** [comment]
Tested `helloworld.py` on a fresh device and confirmed it works with the following configs:

* macOS 10.12.6
  * python 2.7.10
  * python 3.6.3

**Comment by ngmiller** [comment]
`keepkeyctl` test results with `python 2.7.10` on `macOS 10.12.6`

|`keepkeyctl` command|success|notes|
|-|-|-|
|`apply_policy`|:large_orange_diamond:|confirmation shows up on device, but get call exception after confirm|
|`change_pin`|:white_check_mark:||
|`clear_session`|:white_check_mark:||
|`decrypt_keyvalue`|:white_check_mark:||
|`decrypt_message`|:red_circle:|did not test|
|`encrypt_keyvalue`|:white_check_mark:||
|`encrypt_message`|:red_circle:|did not test|
|`ethereum_get_address`|:white_check_mark:||
|`ethereum_sign_tx`|:red_circle:|had to `pip install ethjsonrpc`, timeout on connection|
|`firmware_update`|:white_check_mark:||
|`get_address`|:white_check_mark:||
|`get_entropy`|:white_check_mark:||
|`get_features`|:white_check_mark:||
|`get_public_node`|:white_check_mark:||
|`list`|:white_check_mark:||
|`list_coins`|:white_check_mark:||
|`load_device`|:red_circle:|did not test|
|`ping`|:white_check_mark:||
|`recovery_device`|:white_check_mark:||
|`reset_device`|:white_check_mark:||
|`set_label`|:white_check_mark:||
|`sign_message`|:white_check_mark:||
|`verify_message`|:white_check_mark:||
|`wipe_device`|:white_check_mark:||

**Comment by ngmiller** [comment]
`keepkeyctl` test results with `python 2.7.12` on `Ubuntu 16.04.3 LTS` via VirtualBox

|`keepkeyctl` command|success|notes|
|-|-|-|
|`apply_policy`|:white_check_mark:|enabled/disabled ShapeShift policy successfully|
|`change_pin`|:white_check_mark:||
|`clear_session`|:white_check_mark:||
|`decrypt_keyvalue`|:white_check_mark:||
|`decrypt_message`|:red_circle:|did not test|
|`encrypt_keyvalue`|:white_check_mark:||
|`encrypt_message`|:red_circle:|did not test|
|`ethereum_get_address`|:white_check_mark:||
|`ethereum_sign_tx`|:red_circle:|had to `pip install ethjsonrpc`, timeout on connection|
|`firmware_update`|:white_check_mark:||
|`get_address`|:white_check_mark:||
|`get_entropy`|:white_check_mark:||
|`get_features`|:white_check_mark:||
|`get_public_node`|:white_check_mark:||
|`list`|:white_check_mark:||
|`list_coins`|:white_check_mark:||
|`load_device`|:red_circle:|did not test|
|`ping`|:white_check_mark:||
|`recovery_device`|:white_check_mark:||
|`reset_device`|:white_check_mark:||
|`set_label`|:white_check_mark:||
|`sign_message`|:white_check_mark:||
|`verify_message`|:white_check_mark:||
|`wipe_device`|:white_check_mark:||

**Comment by solipsis** [comment]
`keepkeyctl` test results with `python 3.6` on `MacOS 10.12.6`

|`keepkeyctl` command|success|notes|
|-|-|-|
|`apply_policy`|:white_check_mark:|
|`change_pin`|:white_check_mark:||
|`clear_session`|:white_check_mark:||
|`decrypt_keyvalue`|:white_check_mark:||
|`decrypt_message`|:red_circle:|did not test|
|`encrypt_keyvalue`|:red_circle:|message to encrypt interpreted in wrong format|
|`encrypt_message`|:red_circle:|failure. message to encrypt interpreted in wrong format|
|`ethereum_get_address`|:white_check_mark:||
|`ethereum_sign_tx`|:red_circle:|had to `pip install ethjsonrpc`, timeout on connection|
|`firmware_update`|:white_check_mark:||
|`get_address`|:white_check_mark:||
|`get_entropy`|:white_check_mark:||
|`get_features`|:white_check_mark:||
|`get_public_node`|:white_check_mark:||
|`list`|:white_check_mark:||
|`list_coins`|:white_check_mark:||
|`load_device`|:red_circle:|did not test|
|`ping`|:white_check_mark:||
|`recovery_device`|:white_check_mark:||
|`reset_device`|:white_check_mark:||
|`set_label`|:white_check_mark:||
|`sign_message`|:white_check_mark:||
|`verify_message`|:white_check_mark:||
|`wipe_device`|:white_check_mark:||

**Comment by ngmiller** [comment]
Verified `xpub` functionality on Ubuntu 16.04.3 LTS as per [support desk instructions](https://support.keepkey.com/support/solutions/articles/6000098264-keepkey-xpub-ubuntu-linux-)

**Comment by solipsis** [comment]
xpub functionality also verified on macOS 10.12.6

**Comment by ngmiller** [comment]
`keepkeyctl` test results with `python 2.7.14` on `Windows 10`

|`keepkeyctl` command|success|notes|
|-|-|-|
|`apply_policy`|:white_check_mark:|enabled/disabled ShapeShift policy successfully|
|`change_pin`|:white_check_mark:||
|`clear_session`|:white_check_mark:||
|`decrypt_keyvalue`|:white_check_mark:||
|`decrypt_message`|:red_circle:|did not test|
|`encrypt_keyvalue`|:white_check_mark:||
|`encrypt_message`|:red_circle:|did not test|
|`ethereum_get_address`|:white_check_mark:||
|`firmware_update`|:red_circle:|does not work|
|`get_address`|:white_check_mark:||
|`get_entropy`|:white_check_mark:||
|`get_features`|:white_check_mark:||
|`get_public_node`|:white_check_mark:||
|`list`|:white_check_mark:||
|`list_coins`|:white_check_mark:||
|`load_device`|:red_circle:|did not test|
|`ping`|:white_check_mark:||
|`recovery_device`|:white_check_mark:||
|`reset_device`|:white_check_mark:||
|`set_label`|:white_check_mark:||
|`sign_message`|:white_check_mark:||
|`verify_message`|:white_check_mark:||
|`wipe_device`|:white_check_mark:||

**Pull request closed without merging**
