### PR TITLE
Update client build with device-protocol v4.0.0

### PR DESCRIPTION
**Pull request by ngmiller**
* Rebuilt `keepkeylib/*` files with `v4.0.0` of the device-protocol
* Added BitcoinCash as a valid coin type in the client

### CODE REVIEW

**Comment by ngmiller** [comment]
@kyuupichan @fyookball
This branch contained compiled protobuf definitions corresponding to the latest version of the keepkey firmware, which supports Bitcoin Cash. I've been having some trouble getting a development version of [`fyookball/electrum`](https://github.com/fyookball/electrum) to build. Do you have a moment to review these changes and/or build them into Electrum to verify your BCH needs are supported with this lib?

**Comment by kyuupichan** [comment]
@ngmiller I can confirm 0.9.0 is good to sign transactions in both Electrum head and Electron Cash head (i.e. with the commits below).  However both had to be modified because the removal of decrypt_message broke the clients.

https://github.com/spesmilo/electrum/commit/21e0cd92371d222d2bcaf74782c4f1fc87dda280
https://github.com/fyookball/electrum/commit/0ecc9f9df8e2a3bbfdd92dadc775bdbcc5053051

**Comment by ngmiller** [comment]
@kyuupichan Thanks. Apologies for the breaking change there, we should have tagged 1.0.0. From here on out, we will be tagging the major version to match the firmware version, in this case, `4.0.0`

**Comment by bgok** [comment]
[(S) Merge and release python KK 4.0.0](https://trello.com/c/1dyGF7UO/5-s-merge-and-release-python-kk-400)

**Pull request merged**
